export const vCreate = () => {
  return {
    // req_headers['name']: { type: 'string', required: true },
    // req_headers['value']: { type: 'string', required: true },
    // req_headers['required']: { type: 'string', required: true },
    // req_headers['example']: { type: 'string', required: true },
    // req_headers['desc']: { type: 'string', required: true },
    // req_query['name']: { type: 'string', required: true },
    // req_query['required:'] { type: 'string', required: true },
    // req_query['example']: { type: 'string', required: true },
    // req_query['desc']: { type: 'string', required: true },
    // req_body['name']: { type: 'string', required: true },
    // req_body['type:'] { type: 'string', required: true },
    // req_body['required']: { type: 'string', required: true },
    // req_body['example']: { type: 'string', required: true },
    // req_body['desc']: { type: 'string', required: true },
    req_headers_name: { type: 'string', required: false },
    req_headers_value: { type: 'string', required: false },
    req_headers_required: { type: 'string', required: false },
    req_headers_example: { type: 'string', required: false },
    req_headers_desc: { type: 'string', required: false },
    req_query_name: { type: 'string', required: false },
    req_query_required: { type: 'string', required: false },
    req_query_example: { type: 'string', required: false },
    req_query_desc: { type: 'string', required: false },
    req_body_name: { type: 'string', required: false },
    req_body_type: { type: 'string', required: false },
    req_body_required: { type: 'string', required: false },
    req_body_example: { type: 'string', required: false },
    req_body_desc: { type: 'string', required: false },
  }
}